// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Tekademy1C.Features.Admins.Libraries
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Library")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class LibraryFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Admins/Libraries", "Library", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "UploadLibraries .feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
#line hidden
#line 6
await testRunner.GivenAsync("User navigates to takademy \"https://tekademy-admin-app.vercel.app/auth/login\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
 await testRunner.WhenAsync("User enters  email \"superAdmin@tekademy.io\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
 await testRunner.AndAsync("User enters  password \"Password123!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
 await testRunner.AndAsync("User clicks on login button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Admins/Libraries/UploadLibraries .feature.ndjson", 18);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Upload a file to Library")]
        [global::NUnit.Framework.CategoryAttribute("tag1")]
        public async global::System.Threading.Tasks.Task UploadAFileToLibrary()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Upload a file to Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 13
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.AndAsync("user enter descriptions \"Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Documents\\clinc\\Chenot Palace Weggis.docx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.AndAsync("user click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
 await testRunner.ThenAsync("A message should be displayed \"Resource uploaded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Upload a file to Library uncheck Publish immediately")]
        public async global::System.Threading.Tasks.Task UploadAFileToLibraryUncheckPublishImmediately()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Upload a file to Library uncheck Publish immediately", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 24
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
 await testRunner.AndAsync("user enter descriptions \"Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Documents\\clinc\\Chenot Palace Weggis.docx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.AndAsync("user unclick Publish immediately", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
 await testRunner.AndAsync("user click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.ThenAsync("A message should be displayed \"Resource uploaded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Upload a video less than 50MB.to Library")]
        public async global::System.Threading.Tasks.Task UploadAVideoLessThan50MB_ToLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Upload a video less than 50MB.to Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 36
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.AndAsync("user enter descriptions \"Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
 await testRunner.AndAsync("user select a file \"c:\\Users\\NUGA\\Videos\\IMG_5567.MOV\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
 await testRunner.AndAsync("user click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.ThenAsync("A message should be displayed \"File must be at most 50 MB.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Upload a video to Library")]
        public async global::System.Threading.Tasks.Task UploadAVideoToLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Upload a video to Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 47
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
 await testRunner.AndAsync("user enter descriptions \"Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
 await testRunner.AndAsync("user click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
 await testRunner.ThenAsync("A message should be displayed \"Resource uploaded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Upload a video to Library uncheck Publish immediately")]
        public async global::System.Threading.Tasks.Task UploadAVideoToLibraryUncheckPublishImmediately()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Upload a video to Library uncheck Publish immediately", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 58
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.AndAsync("user enter descriptions \"Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
 await testRunner.AndAsync("user unclick Publish immediately", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
 await testRunner.AndAsync("user click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
 await testRunner.ThenAsync("A message should be displayed \"Resource uploaded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Replace a file in Library")]
        public async global::System.Threading.Tasks.Task ReplaceAFileInLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Replace a file in Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 69
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 70
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
 await testRunner.AndAsync("user enter descriptions \"Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Documents\\clinc\\Chenot Palace Weggis.docx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Documents\\clinc\\Cleveland Clinic Executive Heal" +
                        "th.docx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
 await testRunner.AndAsync("user click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
 await testRunner.ThenAsync("A message should be displayed \"Resource uploaded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Remove a file and upload a new one in Library")]
        public async global::System.Threading.Tasks.Task RemoveAFileAndUploadANewOneInLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Remove a file and upload a new one in Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 82
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 83
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
 await testRunner.AndAsync("user enter descriptions \"Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Documents\\clinc\\Chenot Palace Weggis.docx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
 await testRunner.AndAsync("user click on \"Remove\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Documents\\clinc\\Cleveland Clinic Executive Heal" +
                        "th.docx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
 await testRunner.AndAsync("user click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
 await testRunner.ThenAsync("A message should be displayed \"Resource uploaded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Replace a video in Library")]
        public async global::System.Threading.Tasks.Task ReplaceAVideoInLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Replace a video in Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 95
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 96
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 97
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 100
 await testRunner.AndAsync("user enter descriptions \"Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 101
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
 await testRunner.AndAsync("user click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
 await testRunner.ThenAsync("A message should be displayed \"Resource uploaded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Remove a video  and upload a new one in Library")]
        public async global::System.Threading.Tasks.Task RemoveAVideoAndUploadANewOneInLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Remove a video  and upload a new one in Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 107
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 108
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 109
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
 await testRunner.AndAsync("user enter descriptions \"Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
 await testRunner.AndAsync("user click on \"Remove\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
 await testRunner.AndAsync("user click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
 await testRunner.ThenAsync("A message should be displayed \"Resource uploaded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Remove a file or a video from Library")]
        public async global::System.Threading.Tasks.Task RemoveAFileOrAVideoFromLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Remove a file or a video from Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 120
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 121
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 122
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
 await testRunner.AndAsync("user enter descriptions \"Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 126
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Documents\\clinc\\Chenot Palace Weggis.docx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 128
 await testRunner.AndAsync("user click on \"Remove\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 129
 await testRunner.ThenAsync("user is unable to click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Empty title file in Library")]
        public async global::System.Threading.Tasks.Task EmptyTitleFileInLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Empty title file in Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 131
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 132
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
 await testRunner.AndAsync("user enter title \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 136
 await testRunner.AndAsync("user enter descriptions \"Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 137
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Documents\\clinc\\Chenot Palace Weggis.docx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
 await testRunner.AndAsync("user clear title field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
 await testRunner.ThenAsync("user is unable to click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Empty category  in Library")]
        public async global::System.Threading.Tasks.Task EmptyCategoryInLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Empty category  in Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 142
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 143
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 144
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 145
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 146
 await testRunner.AndAsync("user enter descriptions \"Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 147
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 148
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Documents\\clinc\\Chenot Palace Weggis.docx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 149
 await testRunner.ThenAsync("user is unable to click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Empty description in Library")]
        public async global::System.Threading.Tasks.Task EmptyDescriptionInLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Empty description in Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 151
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 152
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 153
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 154
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 155
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 156
 await testRunner.AndAsync("user enter descriptions \"  \"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 157
 await testRunner.AndAsync("user enter tags \"c#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 159
 await testRunner.AndAsync("user click on \"Remove\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 160
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 161
 await testRunner.AndAsync("user click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 162
 await testRunner.ThenAsync("A message should be displayed \"Resource uploaded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Empty tags in Library")]
        public async global::System.Threading.Tasks.Task EmptyTagsInLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Empty tags in Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 164
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 165
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 166
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 167
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 169
 await testRunner.AndAsync("user enter descriptions \"Test automation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 170
 await testRunner.AndAsync("user enter tags \" \"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 171
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 172
 await testRunner.AndAsync("user click on \"Remove\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 173
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 174
 await testRunner.AndAsync("user click on \"Upload\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 175
 await testRunner.ThenAsync("A message should be displayed \"Resource uploaded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify that user can click on cancel button in Library")]
        public async global::System.Threading.Tasks.Task VerifyThatUserCanClickOnCancelButtonInLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify that user can click on cancel button in Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 178
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 179
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 180
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 181
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 182
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 183
 await testRunner.AndAsync("user enter descriptions \" Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 184
 await testRunner.AndAsync("user enter tags \" \"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 185
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 186
 await testRunner.AndAsync("user click on \"Remove\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 187
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 188
 await testRunner.AndAsync("user click on \"Cancel\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 189
 await testRunner.ThenAsync("user redirected to \"Library & Resources\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify that user can click on X button in Library")]
        public async global::System.Threading.Tasks.Task VerifyThatUserCanClickOnXButtonInLibrary()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify that user can click on X button in Library", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 191
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 192
 await testRunner.WhenAsync("user click on \"Library\" menus", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 193
 await testRunner.AndAsync("user click on \"Upload Resource\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 194
 await testRunner.AndAsync("user enter title \"Test Title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 195
 await testRunner.AndAsync("user select categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 196
 await testRunner.AndAsync("user enter descriptions \" Test Description\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 197
 await testRunner.AndAsync("user enter tags \" \"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 198
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 199
 await testRunner.AndAsync("user click on \"Remove\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 200
 await testRunner.AndAsync("user select a file \"C:\\Users\\NUGA\\Pictures\\Camera Roll\\WIN_20260115_03_11_12_Pro." +
                        "mp4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 201
 await testRunner.AndAsync("user click on x button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 202
 await testRunner.ThenAsync("user redirected to \"Library & Resources\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
